### ISSUE TITLE
CopBET_main_CH2016data.m calls network label file that's not in repository

### ISSUE THREAD

**Issue by bwinsto2** [anders-s-olsen/CopBET#4]
This file is not inside Atlases. Would be helpful to throw it in there or provide a download link.

<img width="502" alt="Screen Shot 2024-01-24 at 10 35 26 AM" src="https://github.com/anders-s-olsen/CopBET/assets/61159065/b8b531df-b54b-47b4-8239-607674a543bc">

**Comment by anders-s-olsen** [comment]
The file is now added. Thanks for notifying about this issue!
